package mtmt.MTMT_BE.domain.user.domain.type;

public enum Category {

    // SPORT
    SPORT_SOCCER,
    SPORT_BASKETBALL,
    SPORT_BADMINTON,
    SPORT_BASEBALL,
    SPORT_TENNIS,
    SPORT_WEIGHT,
    SPORT_PILATES,
    SPORT_BOXING,
    SPORT_SWIMMING,
    SPORT_CLIMBING,

    // ART
    ART_DRAWING,
    ART_WATERCOLOR,
    ART_ACRYLIC,
    ART_DIGITAL_DRAWING,
    ART_ANIMATION,
    ART_WEBTOON,
    ART_GRAPHIC_DESIGN,

    // MUSIC
    MUSIC_AUDITION,
    MUSIC_GUITAR,
    MUSIC_VOCAL,
    MUSIC_PIANO,
    MUSIC_COMPOSITION,
    MUSIC_MIDI,
    MUSIC_RAP,
    MUSIC_THEORY,
    MUSIC_HOMERECORDING,
    MUSIC_DRUM,

    // ACADEMIC
    ACADEMIC_MATH_I,
    ACADEMIC_ENGLISH,
    ACADEMIC_KOREAN,
    ACADEMIC_CSAT,
    ACADEMIC_SCIENCE,
    ACADEMIC_CALCULUS,
    ACADEMIC_MIDTERM,
    ACADEMIC_HISTORY,
    ACADEMIC_CS,
    ACADEMIC_SOCIAL
}
